1 - Importar Arquivos e Bibliotecas

In [13]:
import pandas as pd
from IPython.display import display
import pathlib
import win32com.client as win32

In [14]:
# Para ler os arquivos presentes na pasta, como os emails, lojas e vendas

emails = pd.read_excel(r'Bases de Dados/Emails.xlsx')
lojas = pd.read_csv(r'Bases de Dados/Lojas.csv', encoding='latin1', sep=';')
vendas = pd.read_excel(r'Bases de Dados/Vendas.xlsx')

# Visualização de cada arquivo

display(emails)
display(lojas)
display(vendas)

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,caioriberio+helena@gmail.com
1,Shopping Midway Mall,Alice,caioriberio+alice@gmail.com
2,Norte Shopping,Laura,caioriberio+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,caioriberio+manuela@gmail.com
4,Shopping União de Osasco,Valentina,caioriberio+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,caioriberio+sophia@gmail.com
6,Rio Mar Recife,Isabella,caioriberio+isabella@gmail.com
7,Salvador Shopping,Heloisa,caioriberio+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,caioriberio+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,caioriberio+julia@gmail.com
10,Ribeirão Shopping,Lorena,caioriberio+lorena@gmail.com
11,Shopping Morumbi,Livia,caioriberio+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,caioriberio+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,caioriberio+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,caioriberio+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,caioriberio+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,caioriberio+arthur@gmail.com
17,Shopping Recife,Heitor,caioriberio+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,caioriberio+bernardo@gmail.com
19,Shopping SP Market,Davi,caioriberio+davi@gmail.com
20,Shopping Eldorado,Theo,caioriberio+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,caioriberio+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,caioriberio+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,caioriberio+pedro@gmail.com
24,Shopping Barra,Benjamin,caioriberio+benjamin@gmail.com
25,Diretoria,Diretoria,caioriberio+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

2 - Criar uma tabela para cada loja e definir o dia do indicador

In [15]:
# atribui um ID a cada loja

vendas = vendas.merge(lojas, on='ID Loja')

# Exemplo

display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2019-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [16]:
# Criar um dicionário com todas as lojas e seus dados

dicionario_lojas = {}
for loja in lojas['Loja']:
    dicionario_lojas[loja] = vendas.loc[vendas['Loja']==loja, :]

# Exemplo

display(dicionario_lojas['Iguatemi Esplanada'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
26,21,2019-01-02,1,Camisa Gola V Listrado,2,116,232,Iguatemi Esplanada
44,34,2019-01-02,1,Sapato Listrado,1,363,363,Iguatemi Esplanada
...,...,...,...,...,...,...,...,...
100847,69899,2019-12-25,1,Sapato Xadrez,4,368,1472,Iguatemi Esplanada
100854,69903,2019-12-25,1,Terno Liso,5,720,3600,Iguatemi Esplanada
100894,69928,2019-12-25,1,Meia,1,30,30,Iguatemi Esplanada
100920,69944,2019-12-25,1,Gorro Xadrez,5,85,425,Iguatemi Esplanada
100921,69944,2019-12-25,1,Sapato Xadrez,2,368,736,Iguatemi Esplanada

In [17]:
# Localizar o dia indicador, que nesse caso será a data mais recente, por isso é utilizado o .max()

dia_indicador = vendas['Data'].max()

3 - Salvar na Pasta de Backup

In [18]:
# Identificar se a pasta de cada loja já existe e caso ainda não tenha, ela será criada

caminho_backup = pathlib.Path(r'Backup Arquivos Lojas')

arquivos_pastas_backup = caminho_backup.iterdir()
lista_backup_lojas = [arquivo.name for arquivo in arquivos_pastas_backup]

for loja in dicionario_lojas:
    if loja not in lista_backup_lojas:
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()

# Para poder salvar o arquivo dentro das respectivas pastas de backup

    nome_do_arquivo = f'{dia_indicador.day}_{dia_indicador.month}_{loja}.xlsx'
    local_do_arquivo = caminho_backup / loja / nome_do_arquivo
    dicionario_lojas[loja].to_excel(local_do_arquivo)

4 - Calcular o indicador para loja +

5 - Disparador de E-mails

In [19]:
# Definição das metas

meta_faturamento_dia = 1000
meta_faturamento_ano = 16500000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [20]:
# Calcular o faturamento do dia e o faturamento total de cada loja
for loja in dicionario_lojas:

    vendas_loja = dicionario_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==dia_indicador, :]

    # Faturamento

    faturamento_ano = vendas_loja['Valor Final'].sum()
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()

    # Diversidade de produtos: vê a quantidade de produtos.

    quantidade_prod_ano = len(vendas_loja['Produto'].unique())
    quantidade_prod_dia = len(vendas_loja_dia['Produto'].unique())

    # Ticket Médio

    # valor para o ano

    valor_vendas = vendas_loja.groupby('Código Venda').sum(numeric_only=True)
    ticket_medio_ano = valor_vendas['Valor Final'].mean()

    # valor para o dia

    valor_vendas_dia = vendas_loja_dia.groupby('Código Venda').sum(numeric_only=True)
    ticket_medio_dia = valor_vendas_dia['Valor Final'].mean()
    outlook = win32.Dispatch('outlook.application')

    # Envio dos e-mails

    nome = emails.loc[emails['Loja']==loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = emails.loc[emails['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}'

    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'

    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'

    if quantidade_prod_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'

    if quantidade_prod_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'

    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'

    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'

    mail.HTMLBody = f'''
    <p>Olá, espero que esteja bem, {nome}</p>

    <p>O resultado do dia <strong>{dia_indicador.day}/{dia_indicador.month}</strong> da <strong>loja {loja}</strong> foi:</p>

    <table>
        <tr>
            <th>Indicador</th>
            <th>Valor Dia</th>
            <th>Meta Dia</th>
            <th>Cenário Dia</th>
        </tr>
        <tr>
            <td>Faturamento</td>
            <td style="text-align: center;">R${faturamento_dia:.2f}</td>
            <td style="text-align: center;">R${meta_faturamento_dia:.2f}</td>
            <td style="text-align: center;"><font color="{cor_fat_dia}">◙</td>
        </tr>
        <tr>
            <td>Diversidade de Produtos</td>
            <td style="text-align: center;">{quantidade_prod_dia}</td>
            <td style="text-align: center;">{meta_qtdeprodutos_dia}</td>
            <td style="text-align: center;"><font color="{cor_qtde_dia}">◙</td>
        </tr>
        <tr>
            <td>Ticket Médio</td>
            <td style="text-align: center;">R${ticket_medio_dia:.2f}</td>
            <td style="text-align: center;">R${meta_ticketmedio_dia:.2f}</td>
            <td style="text-align: center;"><font color="{cor_ticket_dia}">◙</td>
        </tr>
    </table>
    <br>
    <table>
        <tr>
            <th>Indicador</th>
            <th>Valor Ano</th>
            <th>Meta Ano</th>
            <th>Cenário Ano</th>
        </tr>
        <tr>
            <td>Faturamento</td>
            <td style="text-align: center;">R${faturamento_ano:.2f}</td>
            <td style="text-align: center;">R${meta_faturamento_ano:.2f}</td>
            <td style="text-align: center;"><font color="{cor_fat_ano}">◙</td>
        </tr>
        <tr>
            <td>Diversidade de Produtos</td>
            <td style="text-align: center;">{quantidade_prod_ano}</td>
            <td style="text-align: center;">{meta_qtdeprodutos_ano}</td>
            <td style="text-align: center;"><font color="{cor_qtde_ano}">◙</td>
        </tr>
        <tr>
            <td>Ticket Médio</td>
            <td style="text-align: center;">R${ticket_medio_ano:.2f}</td>
            <td style="text-align: center;">R${meta_ticketmedio_ano:.2f}</td>
            <td style="text-align: center;"><font color="{cor_ticket_ano}">◙</td>
        </tr>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>
    <p>Att., Caio Luiz.</p>
    '''
    # Anexos
    attachment = pathlib.Path.cwd() / caminho_backup / loja / f'{dia_indicador.day}_{dia_indicador.month}_{loja}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    print(f'E-mail da loja {loja} enviado.')

E-mail da loja Iguatemi Esplanada enviado.
E-mail da loja Shopping Midway Mall enviado.
E-mail da loja Norte Shopping enviado.
E-mail da loja Shopping Iguatemi Fortaleza enviado.
E-mail da loja Shopping União de Osasco enviado.
E-mail da loja Shopping Center Interlagos enviado.
E-mail da loja Rio Mar Recife enviado.
E-mail da loja Salvador Shopping enviado.
E-mail da loja Rio Mar Shopping Fortaleza enviado.
E-mail da loja Shopping Center Leste Aricanduva enviado.
E-mail da loja Ribeirão Shopping enviado.
E-mail da loja Shopping Morumbi enviado.
E-mail da loja Parque Dom Pedro Shopping enviado.
E-mail da loja Bourbon Shopping SP enviado.
E-mail da loja Palladium Shopping Curitiba enviado.
E-mail da loja Passei das Águas Shopping enviado.
E-mail da loja Center Shopping Uberlândia enviado.
E-mail da loja Shopping Recife enviado.
E-mail da loja Shopping Vila Velha enviado.
E-mail da loja Shopping SP Market enviado.
E-mail da loja Shopping Eldorado enviado.
E-mail da loja Shopping Ibirapuera enviado.
E-mail da loja Novo Shopping Ribeirão Preto enviado.
E-mail da loja Iguatemi Campinas enviado.
E-mail da loja Shopping Barra enviado.

6 - Ranking das lojas com vendas dia e ano

In [24]:
faturamento_lojas = vendas.groupby('Loja')[['Valor Final']].sum()
faturamento_lojas_ano = faturamento_lojas.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_ano)

nome_do_arquivo = f'{dia_indicador.day}_{dia_indicador.month}_Ranking Anual.xlsx'
faturamento_lojas_ano.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_do_arquivo))

vendas_dia = vendas.loc[vendas['Data']==dia_indicador, :]
faturamento_lojas_dia = vendas_dia.groupby('Loja')[['Valor Final']].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)
display(faturamento_lojas_dia)

nome_do_arquivo = f'{dia_indicador.day}_{dia_indicador.month}_Ranking Dia.xlsx'
faturamento_lojas_dia.to_excel(r'Backup Arquivos Lojas\{}'.format(nome_do_arquivo))

                                  Valor Final
Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

                                  Valor Final
Loja
Salvador Shopping                        3950
Novo Shopping Ribeirão Preto             3400
Center Shopping Uberlândia               2651
Shopping Eldorado                        2391
Shopping Center Interlagos               1582
Shopping Recife                          1366
Norte Shopping                           1259
Shopping União de Osasco                 1207
Shopping Vila Velha                       937
Bourbon Shopping SP                       676
Ribeirão Shopping                         650
Shopping Center Leste Aricanduva          485
Palladium Shopping Curitiba               381
Rio Mar Shopping Fortaleza                368
Shopping Midway Mall                      170
Shopping Ibirapuera                       118